### ISSUE TITLE
SVtyper on lumpy traditional vcf

### ISSUE THREAD

**Issue by nitinra** [hall-lab/svtyper#121]
Hi all,
I am trying to run svtyper from vcf files from lumpy. I have followed the tutorial posted on the lumpy github to produce the vcf. This is the error I am getting while using svtyper:

<Warning: --split_bam (-S) is deprecated. Ignoring GC1601.splitters.bam.
Traceback (most recent call last):
  File "/work/nitinr/svtyper2_env/bin/svtyper", line 11, in <module>
    load_entry_point('svtyper==0.7.1', 'console_scripts', 'svtyper')()
  File "/work/nitinr/svtyper2_env/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
    sys.exit(main())
  File "/work/nitinr/svtyper2_env/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
    args.max_ci_dist)
  File "/work/nitinr/svtyper2_env/lib/python2.7/site-packages/svtyper/classic.py", line 150, in sv_genotype
    sample = Sample.from_bam(bam_list[i], num_samp, min_lib_prevalence)
  File "/work/nitinr/svtyper2_env/lib/python2.7/site-packages/svtyper/parsers.py", line 665, in from_bam
    name = bam.header['RG'][0]['SM']
  File "pysam/libcalignmentfile.pyx", line 547, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
KeyError: 'RG'>

**Comment by Huangwenxuan666888** [comment]
Hi,
I encountered the same issue; did you manage to resolve it in the end?
