### ISSUE TITLE
Issue while running the executable. 

### ISSUE THREAD

**Issue by kghimire09** [hall-lab/svtyper#122]
Hi, 
I'm trying to use svtyper on my mac and after installation when I try to run the executable I get this error:

% svtyper
Traceback (most recent call last):
  File "/Users/kshitizghimire/miniconda3/bin/svtyper", line 5, in <module>
    from svtyper.classic import cli
  File "/Users/kshitizghimire/miniconda3/lib/python3.6/site-packages/svtyper/classic.py", line 416
    print '--------------------------'
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('--------------------------')?

Any suggestions on how to fix this?

**Comment by joehagmann** [comment]
Identical error here with current version 0.7.1. Installation was fine, see below.

I'd appreciate any help.

```
-> % pip install git+https://github.com/hall-lab/svtyper.git
Collecting git+https://github.com/hall-lab/svtyper.git
  Cloning https://github.com/hall-lab/svtyper.git to /tmp/pip-req-build-dhblr_1z
  Running command git clone -q https://github.com/hall-lab/svtyper.git /tmp/pip-req-build-dhblr_1z
Requirement already satisfied: cytoolz>=0.8.2 in /home1/joerg/.local/lib/python3.8/site-packages (from svtyper==0.7.1) (0.11.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from svtyper==0.7.1) (1.17.4)
Requirement already satisfied: pysam>=0.15.0 in /home1/joerg/.local/lib/python3.8/site-packages (from svtyper==0.7.1) (0.17.0)
Requirement already satisfied: scipy in /home1/joerg/libs/python/lib/python3.6/site-packages/scipy-1.5.4-py3.6-linux-x86_64.egg (from svtyper==0.7.1) (1.5.4)
Requirement already satisfied: toolz>=0.8.0 in /home1/joerg/.local/lib/python3.8/site-packages (from cytoolz>=0.8.2->svtyper==0.7.1) (0.11.1)
Building wheels for collected packages: svtyper
  Building wheel for svtyper (setup.py) ... done
  Created wheel for svtyper: filename=svtyper-0.7.1-py3-none-any.whl size=59453 sha256=af943485f07cddfa3a91257a86ee4c957ba8a5df7e315ec9822098b50ae7cfe8
  Stored in directory: /tmp/pip-ephem-wheel-cache-fy1s5g3k/wheels/aa/59/45/243b042cfeaea565e5590bb8dde3931f059783f29d6cd5d3d1
Successfully built svtyper
Installing collected packages: svtyper
Successfully installed svtyper-0.7.1
```

**Comment by joehagmann** [comment]
Setting the shebang of the svtyper executable to a python3 binary solved this issue. Or installing svtyper in an environment where `which python` points to a python3 installation.
Please consider updating the README where python2.7.x is listed as a requirement.

**Comment by mrburke00** [comment]
@joehagmann Could you elaborate on how you fixed this? Did you manipulate the shebang at `/Users/kshitizghimire/miniconda3/bin/svtype`?

**Comment by wbsimey** [comment]
I had the same issue. I believe it is a python version issue. I have python 3, but I believe SVTyper requires v 2.7. So I did the following:
**Create a virtual environment with Python 2**
`virtualenv -p /path/to/python2/bin/python2 venv`

**Activate the virtual environment**
`source venv/bin/activate`

**Install svtyper within the virtual environment**
`pip install git+https://github.com/hall-lab/svtyper.git`

**Run your svtyper command within the virtual environment**
`svtyper -B input.bam -S input.splitters.bam -i output.vcf > output_genotype.vcf`
(NOTE: I got the message `"Warning: --split_bam (-S) is deprecated. Ignoring input.splitters.bam"`

Deactivate the virtual environment when done
`deactivate`

**Comment by yqlan** [comment]
did anyone fix this problem?

appreciate it.
