### ISSUE TITLE
svtyper on lumpy vcf

### ISSUE THREAD

**Issue by lurens** [hall-lab/svtyper#14]
hi
I ran lumpy and got the vcf output file.
I would like to run svtyper but i keep getting this error message:
Traceback (most recent call last):
  File "./svtyper", line 1078, in <module>
    sys.exit(main())
  File "./svtyper", line 1070, in main
    args.debug)
  File "./svtyper", line 767, in sv_genotype
    sample = Sample(bam_list[i], spl_bam_list[i], num_samp)
  File "./svtyper", line 709, in __init__
    self.name = bam.header['RG'][0]['SM']
KeyError: 'RG'

Is it related to the -M issue?
Thanks

**Comment by cc2qe** [comment]
probably not in this case. Do your BAM files have read groups? if not, i recommend https://github.com/ekg/bamaddrg to add them
