### ISSUE TITLE
Something funny about reading header

### ISSUE THREAD

**Issue by ryanlayer** [hall-lab/svtyper#23]
I am getting the following error:

```
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u6000294/src/svtyper/svtyper", line 1129, in <module>
    sys.exit(main())
  File "/uufs/chpc.utah.edu/common/home/u6000294/src/svtyper/svtyper", line 1121, in main
    args.debug)
  File "/uufs/chpc.utah.edu/common/home/u6000294/src/svtyper/svtyper", line 818, in sv_genotype
    vcf.add_header(header)
  File "/uufs/chpc.utah.edu/common/home/u6000294/src/svtyper/svtyper", line 67, in add_header
    self.add_info(*[b.split('=')[1] for b in r.findall(a)])
IndexError: list index out of range
```

The offending line appears to be

```
##INFO=<ID=GQT_0,Number=1,Type=Float,Description="GQT maf result from phenotype:'' genotype:'maf()>0'">
```

**Comment by cc2qe** [comment]
ah, i bet this is because it's got a ">" in it and i did a bad job of string parsing
