### ISSUE TITLE
'module' object has no attribute 'AlignmentFile'

### ISSUE THREAD

**Issue by srynobio** [hall-lab/svtyper#36]
Hello, 

I'm doing a little testing with version 0.1.0 and I've run into an issue.

my command based on the svtyper usage statement:

```bash
svtyper -B 101263-101263.bam -i 101263-101263.bam_temp.vcf -o result.test.vcf
```

And the result:

```bash
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/ucgdstor/common/apps/ember.arches/svtyper/0.1.0/svtyper", line 1519, in <module>
    sys.exit(main())
  File "/uufs/chpc.utah.edu/common/home/ucgdstor/common/apps/ember.arches/svtyper/0.1.0/svtyper", line 1514, in main
    args.dump)
  File "/uufs/chpc.utah.edu/common/home/ucgdstor/common/apps/ember.arches/svtyper/0.1.0/svtyper", line 1152, in sv_genotype
    bam_list = [pysam.AlignmentFile(b, 'rb') for b in bam_string.split(',')]
AttributeError: 'module' object has no attribute 'AlignmentFile'
```

Which made me think that pysam was not installed but:

```bash
$ python
Python 2.7.3 (default, Mar 28 2013, 15:20:19)
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>>
```

And of course the usage statement works so it's finding pysam:

```bash
usage: svtyper [-h] -B BAM [-i VCF] [-o VCF] [-l JSON] [-m INT] [-n INT] [--split_weight FLOAT] [--disc_weight FLOAT] [--debug] [--dump STR]
svtyper: error: argument -B/--bam is required
```

Any ideas?

--Shawn

**Comment by cc2qe** [comment]
Hi Shawn,

Pysam updated their variable names, I believe in version 0.8.3 or so. Can you check what version of pysam you're on?

```
python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pysam
>>> pysam.__version__
'0.9.0'
```

**Comment by srynobio** [comment]
```bash
>>> import pysam
>>> pysam.__version__
'0.7.5'
>>>
```

**Comment by cc2qe** [comment]
yeah 0.7.5 won't work with the newer SVTyper. Try upgrading pysam. this will also enable CRAM support

**Comment by srynobio** [comment]
I'll update and close if it resolves.

**Comment by srynobio** [comment]
Updated to 0.9 and the issue went away.  Thanks for your help.
