### ISSUE TITLE
KeyError: 'MATEID'

### ISSUE THREAD

**Issue by YiweiNiu** [hall-lab/svtyper#64]
Hi,

I'm running svtyper on the output of Delly2. Then I got these error messages:
```
Traceback (most recent call last):
  File "/home/work01/tools/SVTyper/svtyper/svtyper", line 1808, in <module>
    sys.exit(main())
  File "/home/work01/tools/SVTyper/svtyper/svtyper", line 1803, in main
    args.max_reads)
  File "/home/work01/tools/SVTyper/svtyper/svtyper", line 1480, in sv_genotype
    if var.info['MATEID'] in breakend_dict:
KeyError: 'MATEID'
```
Thanks!

**Comment by RSherman15** [comment]
I'm getting a similar KeyError, for the CIPOS field:

.. svtyper/classic.py", line 262, in sv_genotype
    ciA = map(int, var.info['CIPOS'].split(','))
KeyError: 'CIPOS'

I assume that this is because my vcf has no CIPOS field -- it was generated with Sniffles, not Lumpy, as I'm trying to see if I can use svtyper to genotype variants from Illumina reads (bam file) given a vcf which was generated from long reads. 

Are there certain fields which are required in the vcf such as MATEID (which is also not in my vcf) and CIPOS, and if so, is that documented somewhere?

Thanks!

**Comment by ernfrid** [comment]
You are correct in your assumptions, but there isn't a documented list.

Looking quickly through the code, it would appear that MATEID, END, CIPOS, CIEND and SVTYPE are all required.

Furthermore, the only supported variant types are BND, DEL, DUP or INV.

**Comment by RSherman15** [comment]
Thanks!

**Comment by jamesdalg** [comment]
@RSherman15 were you ever able to get this working on sniffles?
